version: "3.8"

services:
  local_backend:
    container_name: local_backend
    image: local/backend
    build:
      context: ./chat-backend-template
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3001:8080"

  local_frontend:
    container_name: local_frontend
    image: local/frontend
    build:
      context: ./chat-ui-template
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./configs:/etc/nginx/conf.d
