version: '3.8'

services:
  backend:
    container_name: template_backend
    image: template/backend
    build: 
      context: ./chat-backend-template
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8081:8081"

  frontend:
    container_name: template_frontend
    image: template/frontend
    build: 
      context: ./chat-ui-template
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./configs:/etc/nginx/conf.d